# Configuración de base de datos
db.url=jdbc:postgresql://mail.tecnoweb.org.bo:5432/db_agenda"
db.user=usuario agenda
db.password=password

smtp.gmail.user=[EMAIL_ADDRESS]
smtp.gmail.appPassword=password




PAGOFACIL_BASE_URL=https://masterqr.pagofacil.com.bo/api/services/v2
PAGOFACIL_TOKEN_SERVICE=token service
PAGOFACIL_TOKEN_SECRET=token secret
PAGOFACIL_COMMERCE_ID=commerce id
PAGOFACIL_CALLBACK_URL=callback url
PAGOFACIL_RETURN_URL=return url
PAGOFACIL_TIMEOUT=30
PAGOFACIL_ENABLE_LOGS=true
PAGOFACIL_ENVIRONMENT=sandbox